"""Yantra Saarthi Channels - Unified messaging channel abstraction."""
from .unified import (
    ChannelBase,
    ChannelMessage,
    ChannelRegistry,
    ChannelType,
    create_default_registry,
    DiscordChannel,
    EmailChannel,
    IRCChannel,
    MatrixChannel,
    SignalChannel,
    SlackChannel,
    TeamsChannel,
    TelegramChannel,
    WebChatChannel,
    WebhookChannel,
    WhatsAppChannel,
)

__all__ = [
    "ChannelBase",
    "ChannelMessage",
    "ChannelRegistry",
    "ChannelType",
    "create_default_registry",
    "DiscordChannel",
    "EmailChannel",
    "IRCChannel",
    "MatrixChannel",
    "SignalChannel",
    "SlackChannel",
    "TeamsChannel",
    "TelegramChannel",
    "WebChatChannel",
    "WebhookChannel",
    "WhatsAppChannel",
]
