name: Issue Auto-Processing

on:
  issues:
    types: [opened, labeled, assigned]

jobs:
  process-issue:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests python-dotenv
    
    - name: Process issue automatically
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const issue = context.payload.issue;
          const labels = issue.labels.map(label => label.name);
          const issueBody = issue.body;
          
          // Auto-assign labels based on content
          let autoLabels = [];
          
          if (issueBody.toLowerCase().includes('bug') || issueBody.toLowerCase().includes('error')) {
            autoLabels.push('bug');
          }
          
          if (issueBody.toLowerCase().includes('feature') || issueBody.toLowerCase().includes('enhancement')) {
            autoLabels.push('enhancement');
          }
          
          if (issueBody.toLowerCase().includes('documentation') || issueBody.toLowerCase().includes('docs')) {
            autoLabels.push('documentation');
          }
          
          if (issueBody.toLowerCase().includes('performance') || issueBody.toLowerCase().includes('slow')) {
            autoLabels.push('performance');
          }
          
          // Add auto-detected labels
          if (autoLabels.length > 0) {
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue.number,
              labels: autoLabels
            });
          }
          
          // Auto-assign to appropriate team member
          let assignee = null;
          if (labels.includes('bug')) {
            assignee = 'atulyaai'; // Assign to you for bugs
          } else if (labels.includes('enhancement')) {
            assignee = 'atulyaai'; // Assign to you for features
          }
          
          if (assignee) {
            await github.rest.issues.addAssignees({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue.number,
              assignees: [assignee]
            });
          }
          
          // Create automated response
          let responseBody = `🤖 **Automated Issue Processing Complete**
          
          **Issue Analysis:**
          - 📋 Type: ${autoLabels.length > 0 ? autoLabels.join(', ') : 'General'}
          - 👤 Assigned: ${assignee || 'Auto-assignment pending'}
          - 🏷️ Labels: ${labels.join(', ') || 'None'}
          
          **Next Steps:**
          `;
          
          if (labels.includes('bug')) {
            responseBody += `
            1. 🔍 **Bug Analysis** - Automated debugging will start
            2. 🔧 **Fix Implementation** - Code fixes will be applied
            3. ✅ **Testing** - Automated tests will verify the fix
            4. 📝 **Documentation** - Related docs will be updated
            
            **Expected Resolution**: 24-48 hours`;
          } else if (labels.includes('enhancement')) {
            responseBody += `
            1. 📋 **Feature Planning** - Technical analysis in progress
            2. 🏗️ **Architecture Review** - System design evaluation
            3. 🔨 **Development** - Automated feature implementation
            4. 🧪 **Testing** - Comprehensive testing suite
            
            **Expected Timeline**: 1-2 weeks`;
          } else if (labels.includes('documentation')) {
            responseBody += `
            1. 📖 **Content Analysis** - Reviewing existing documentation
            2. ✍️ **Content Generation** - AI-powered documentation creation
            3. 🔍 **Accuracy Review** - Automated fact-checking
            4. 📝 **Updates Applied** - Documentation automatically updated
            
            **Expected Completion**: 3-5 days`;
          } else {
            responseBody += `
            1. 📋 **Issue Review** - Manual review in progress
            2. 🔄 **Status Update** - You'll be notified of progress
            3. ✅ **Resolution** - Issue will be resolved
            
            **Expected Response**: 24-72 hours`;
          }
          
          responseBody += `
          
          ---
          *This is an automated response from Atulya Tantra AGI system*`;
          
          await github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: issue.number,
            body: responseBody
          });
    
    - name: Auto-fix based on issue type
      if: contains(github.event.issue.labels.*.name, 'bug')
      run: |
        echo "🔧 Running automated bug fixes..."
        python optimize.py
        python setup.py
        
        # Commit fixes
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git diff --staged --quiet || git commit -m "🐛 Auto-fix: Bug fixes applied"
        git push
